using AutoMapper;
using HairPro.Application.Features.BarberShops;
using HairPro.Application.Features.BarberShops.Commands;
using HairPros.Core.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HairPro.Application.MappingProfiles
{

    public class BarberShopProfile : Profile
    {
        public BarberShopProfile()
        {
            CreateMap<CreateBarberShopCommand, BarberShop>()
           .ForMember(dest => dest.Id, opt => opt.Ignore()) // ID AutoGenerated bo‘lsa
           .ForMember(dest => dest.CreatedOn, opt => opt.Ignore()) // SaveChanges() set qiladi
           .ForMember(dest => dest.CreatedBy, opt => opt.Ignore()) // SaveChanges() set qiladi
           .ForMember(dest => dest.UpdatedOn, opt => opt.Ignore()) // Update paytida qo‘shiladi
           .ForMember(dest => dest.UpdatedBy, opt => opt.Ignore());
            CreateMap<BarberShop, BarberShopResponseModel>(); // Entity → Response
          // Command → Entity
            CreateMap<UpdateBarberShopCommand, BarberShop>();
        }
    }


}
